addSbtPlugin("pl.project13.scala" % "sbt-jmh" % "0.4.7")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"           % "2.5.5")
addSbtPlugin("org.jmotor.sbt"            % "sbt-dependency-updates" % "1.2.9")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"                % "1.11.2")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.16")
